# Generated by Django 3.0.6 on 2020-05-24 08:22

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa firmy')),
                ('rating', models.DecimalField(decimal_places=1, default=5, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('street', models.CharField(max_length=128, verbose_name='Ulica i numer mieszkania')),
                ('city', models.CharField(max_length=128, verbose_name='Miasto')),
                ('website', models.URLField(verbose_name='Strona internetowa')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Numer telefonu')),
                ('category', models.ManyToManyField(to='companyapp.Category', verbose_name='Kategoria')),
            ],
        ),
    ]
