# Generated by Django 3.0.6 on 2020-05-14 08:41

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa kategorii')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa firmy')),
                ('rating', models.FloatField()),
                ('address', models.CharField(max_length=128, verbose_name='Adres firmy')),
                ('website', models.URLField(verbose_name='Strona internetowa')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Numer kontaktowy', max_length=31, verbose_name='Numer telefonu')),
                ('category', models.ManyToManyField(to='companyapp.Category')),
            ],
        ),
    ]
