# Generated by Django 3.0.6 on 2020-05-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='company',
            name='y',
            field=models.FloatField(default=0.0),
        ),
    ]
